Repository dpgabot/submission-digitalpublicgoods, pull requests merged in 2021-11, with the labels that each got.

#74 Schema validator
  .github/workflows/main.yml
  .gitignore
  package-lock.json
  package.json
  schemas/schema.js
  scripts/validate-schema.js
Labels: enhancement

#77 BUGFIX: included missing import of conditional submit flag
  .vscode/launch.json
  schemas/schema.js
  scripts/validate-schema.js
Labels: bugfix, bugfix-submission-form

#81 BUGFIX: field-array question types not accepting input
  package-lock.json
  package.json
  pages/api/openPR.js
  pages/form.js
Labels: bugfix, bugfix-submission-form

#82 BUG: fix missing doc section
  schemas/schema.js
Labels: bug
