Repository dpgabot/submission-digitalpublicgoods, pull requests merged in 2021-12, with the labels that each got.

#86 MAINT: Proposed Issue Template
  .github/ISSUE_TEMPLATE/issue_form.yaml
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: maintenance

#91 BUGFIX: Regex standard
  schemas/schema.js
Labels: bugfix, bugfix-submission-form

#93 BLD: assign PR to selected users
  README.md
  package-lock.json
  package.json
  pages/api/openPR.js
Labels: enhancement
